### ISSUE TITLE
Cant create new check

### ISSUE THREAD

**Issue by ttymeh** [Sy3Omda/burp-bounty#1]
I fill out the check wizard and click "ok" but nothing show up in the list and I get this error in the console:

```
java.lang.NullPointerException
	at burp.axk.analyzeRequest(Unknown Source)
	at burp.ee3.analyzeRequest(Unknown Source)
	at burpbounty.BurpBountyExtension.getInsertionPoints(BurpBountyExtension.java:129)
	at burp.dt5.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException
	at burp.axk.analyzeRequest(Unknown Source)
	at burp.ee3.analyzeRequest(Unknown Source)
	at burpbounty.BurpBountyExtension.getInsertionPoints(BurpBountyExtension.java:129)
	at burp.dt5.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException
	at burp.axk.analyzeRequest(Unknown Source)
	at burp.ee3.analyzeRequest(Unknown Source)
	at burpbounty.BurpBountyExtension.getInsertionPoints(BurpBountyExtension.java:129)
	at burp.dt5.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
BurpBountyGui line 1027:
```

Using Burp 2020.7, no other extensions loaded.

**Comment by Sy3Omda** [comment]
make sure you installed the last version of burp bounty and follow the wiki on the author repo.
u could check out his YouTube  channel for more clarifications.
